"""Generate 033_rls_backfill.sql from 011/020/021 (FS-56).

011's RLS policies and 021's intake columns run BEFORE 030 creates the yard/
transport/session tables on a fresh migrations build (their guards skip
absent or still-varchar tables), so 033 re-runs the same guarded blocks after
030/032 have created and converted everything. Generating this file from its
sources keeps them in lockstep — edit 011/020/021, re-run this script.
"""

import re
from pathlib import Path

MIG = Path(__file__).resolve().parents[2] / "database" / "migrations"

blocks = []

for src in ("011_tenant_isolation_rls.sql", "020_erp_integration_tables.sql"):
    text = (MIG / src).read_text()
    for chunk in text.split("\n\n"):
        if "ENABLE ROW LEVEL SECURITY" in chunk and "DO $$" in chunk:
            blocks.append(f"-- from {src}\n{chunk.strip()}")

# 021 is one guarded DO block adding intake/session columns
text21 = (MIG / "021_intake_cross_correlation.sql").read_text()
m = re.search(r"DO \$\$(?:.*\n)*?END \$\$;", text21)
blocks.append("-- from 021_intake_cross_correlation.sql\n" + m.group(0))

header = """-- 033_rls_backfill.sql (FS-56)
-- GENERATED by backend/scripts/gen_033.py from 011/020/021 — do not edit by
-- hand; edit the source migration and re-run the generator.
--
-- Why: 011/020/021 run before 030 creates (and 032 type-converts) the yard/
-- transport/geotab/session/erp tables, so their guards skip those tables on a
-- fresh or legacy build. This file re-runs the exact same guarded, idempotent
-- blocks at the end of the chain when every table exists with final types.
"""

dest = MIG / "033_rls_backfill.sql"
dest.write_text(header + "\n" + "\n\n".join(blocks) + "\n")
print(f"wrote {dest}: {len(blocks)} blocks")
