apiVersion: v1
kind: Service
metadata:
  name: edge-agent
  namespace: omniusgrid
  labels:
    app.kubernetes.io/name: edge-agent
    app.kubernetes.io/component: edge
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: edge-agent
  ports:
    - name: metrics
      port: 9108
      targetPort: 9108
      protocol: TCP
  sessionAffinity: None
