apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omniusgrid

resources:
  - namespace.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - edge-agent-deployment.yaml
  - edge-agent-service.yaml
  - timescaledb-statefulset.yaml
  - redpanda-statefulset.yaml
  - ingress.yaml

configMapGenerator:
  - name: timescaledb-init-scripts
    files:
      - 001_init.sql

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  app.kubernetes.io/part-of: omniusgrid
  app.kubernetes.io/managed-by: kustomize
