"""A fleet where nobody reported their hours showed a green zero on the Compliance tab.

`/api/v1/logistics/compliance/summary` counted HOS violations as

    (d.hos_drive_hours_today or 0) >= 11 or (d.hos_cycle_hours or 0) >= 70

Both columns are nullable, and NULL means the driver has **not reported** — not that they have
driven zero hours. So every unreported driver coerced to 0, cleared both thresholds, and the tab
rendered `activeViolations: 0`. `TransportationManagement` paints that figure GREEN when it is
zero: an all-clear on DOT-regulated hours, generated by the absence of the data that would
decide it.

THE SECOND TIME THIS EXACT CLASS HAS BEEN FOUND ON HOS. The first was
`hosDriveHoursRemaining === 0` on the driver list — `null === 0` is false, so every fleet came
back with no violations and a green "No HOS violations detected" tick. That fix derives the
remaining hours and leaves them NULL when the consumed figure is missing too, and
`HOSComplianceMonitor.check_compliance` collects a `missing_data` list before it judges
anything. The ROLLUP was never brought into line with either.

WHAT CHANGED. A driver is assessable only when both figures are present; violations are counted
over the assessable ones; and the response carries `driversAssessed` / `driversUnassessable` so
a zero can be read. `/logistics_correlation`'s `driver_compliance` block already reported
`unassessable_drivers` for the same reason — the shape existed, on the other endpoint.
"""

from __future__ import annotations

import uuid

import pytest

pytestmark = pytest.mark.asyncio


def _seed_drivers(admin_sync_url, org_id, drivers):
    """`drivers` is a list of (drive_hours_today, cycle_hours) — None for unreported."""
    import psycopg2

    carrier_id = str(uuid.uuid4())
    conn = psycopg2.connect(admin_sync_url)
    conn.autocommit = True
    try:
        with conn.cursor() as cur:
            cur.execute(
                "INSERT INTO carriers (id, organization_id, carrier_name) VALUES (%s, %s, %s)",
                (carrier_id, org_id, "Compliance Carrier"),
            )
            for index, (drive, cycle) in enumerate(drivers):
                cur.execute(
                    "INSERT INTO drivers (id, organization_id, carrier_id, first_name, "
                    "last_name, license_number, hos_drive_hours_today, hos_cycle_hours, "
                    "is_active) "
                    "VALUES (%s, %s, %s, 'D', %s, %s, %s, %s, true)",
                    (str(uuid.uuid4()), org_id, carrier_id, str(index),
                     f"LIC-{uuid.uuid4().hex[:8]}", drive, cycle),
                )
    finally:
        conn.close()


async def _summary(client):
    resp = await client.get("/api/v1/logistics/compliance/summary")
    assert resp.status_code == 200, resp.text
    return resp.json()


class TestAnUnreportedDriverIsNotACompliantOne:
    async def test_a_fleet_that_reported_nothing_is_not_reported_as_clean(
        self, app, client_a, admin_sync_url, seeded_orgs
    ):
        """THE ASSERTION THIS FILE EXISTS FOR. Three drivers, none of whom have reported. The
        old count returned 0 violations, which the tab renders in green."""
        _seed_drivers(admin_sync_url, str(seeded_orgs["org_a_id"]),
                      [(None, None), (None, None), (None, None)])

        summary = await _summary(client_a)

        assert summary["driversAssessed"] == 0
        assert summary["driversUnassessable"] == 3
        assert summary["activeViolations"] == 0, (
            "zero is still the right count — there is nothing to count. The defect was that "
            "nothing distinguished it from a fleet that was actually checked"
        )

    async def test_a_driver_over_the_drive_limit_is_counted(
        self, app, client_a, admin_sync_url, seeded_orgs
    ):
        """The control. A rollup that returned 0 unconditionally would pass the test above."""
        _seed_drivers(admin_sync_url, str(seeded_orgs["org_a_id"]), [(11.5, 20.0)])

        summary = await _summary(client_a)

        assert summary["activeViolations"] == 1
        assert summary["driversAssessed"] == 1
        assert summary["driversUnassessable"] == 0

    async def test_a_driver_over_the_cycle_limit_is_counted(
        self, app, client_a, admin_sync_url, seeded_orgs
    ):
        _seed_drivers(admin_sync_url, str(seeded_orgs["org_a_id"]), [(4.0, 70.0)])
        assert (await _summary(client_a))["activeViolations"] == 1

    async def test_a_compliant_driver_is_not_counted(
        self, app, client_a, admin_sync_url, seeded_orgs
    ):
        """The other control: assessed and under both limits is a real, countable zero."""
        _seed_drivers(admin_sync_url, str(seeded_orgs["org_a_id"]), [(4.0, 20.0)])

        summary = await _summary(client_a)

        assert summary["activeViolations"] == 0
        assert summary["driversAssessed"] == 1
        assert summary["driversUnassessable"] == 0

    async def test_a_partly_reported_driver_is_unassessable_not_compliant(
        self, app, client_a, admin_sync_url, seeded_orgs
    ):
        """Drive hours present, cycle hours missing. The old expression judged this driver on
        `(None or 0) >= 70` and cleared them on a figure nobody had."""
        _seed_drivers(admin_sync_url, str(seeded_orgs["org_a_id"]), [(4.0, None)])

        summary = await _summary(client_a)

        assert summary["driversAssessed"] == 0
        assert summary["driversUnassessable"] == 1

    async def test_the_counts_add_up(self, app, client_a, admin_sync_url, seeded_orgs):
        """A mixed fleet, which is the realistic case and the one where a bare violation count
        is least readable on its own."""
        _seed_drivers(admin_sync_url, str(seeded_orgs["org_a_id"]),
                      [(12.0, 10.0), (4.0, 20.0), (None, None), (None, 5.0)])

        summary = await _summary(client_a)

        assert summary["activeViolations"] == 1
        assert summary["driversAssessed"] == 2
        assert summary["driversUnassessable"] == 2


@pytest.mark.filterwarnings("ignore::pytest.PytestWarning")
class TestTheRollupUsesTheSameLimitsAsTheDriverCheck:
    def test_it_does_not_carry_its_own_copy_of_the_thresholds(self):
        """11.0 and 70.0 appeared here as literals while `HOSComplianceMonitor` held the
        canonical FMCSA values — a third place to update, and the one furthest from anybody
        looking for them."""
        import pathlib

        source = (
            pathlib.Path(__file__).resolve().parents[1] / "app" / "api" / "fleet_logistics.py"
        ).read_text()
        summary = source[source.index("async def compliance_summary"):]
        # `compliance_summary` is currently the LAST function in the file, so slicing to the
        # next decorator raises rather than returning the tail. Take whatever follows it.
        next_decorator = summary.find("\n@")
        if next_decorator != -1:
            summary = summary[:next_decorator]
        assert "activeViolations" in summary, "the slice missed the function body"

        # COMMENTS STRIPPED — rule 37, and this test hit it on its first run. The comment
        # above the fix QUOTES `(d.hos_drive_hours_today or 0) >= 11` while explaining what
        # was wrong with it, so the assertion matched the prose describing the defect and
        # reported the fixed code as unfixed. Prose about a defect gathers around the defect.
        code = "\n".join(
            line for line in summary.splitlines() if not line.lstrip().startswith("#")
        )

        assert "HOSComplianceMonitor.MAX_DRIVE_HOURS_DAY" in code
        assert "HOSComplianceMonitor.MAX_CYCLE_HOURS" in code
        assert ">= 11" not in code and ">= 70" not in code


class TestItIsTenantScoped:
    async def test_another_tenants_drivers_are_not_counted(
        self, app, client_a, client_b, admin_sync_url, seeded_orgs
    ):
        """`drivers` is FORCE row-level security and this handler runs on `get_tenant_db`, so
        the policy is what scopes it — worth asserting on a figure that is now a ratio of two
        counts, where one leaked row moves both."""
        _seed_drivers(admin_sync_url, str(seeded_orgs["org_a_id"]), [(12.0, 10.0)])

        assert (await _summary(client_b))["activeViolations"] == 0
        assert (await _summary(client_b))["driversAssessed"] == 0
