"""Object-store backend for generated export/compliance artifacts.

Exports and compliance reports are generated by a worker on its own pod, but the
download is served by the backend API on a DIFFERENT pod. A pod-local file is
therefore invisible to the API — the download 404s in any multi-pod deployment.
This stores the artifact in S3/SeaweedFS so every pod can reach it, and streams
it back on download.

Gated on ``settings.EXPORT_USE_S3`` so single-node/dev keeps the plain local-disk
path. File-oriented (upload a path, stream by key) rather than the RAG document
store's in-memory bytes, since exports can be large. The aioboto3 session is
injectable so tests can supply a fake client without a live S3.
"""
from __future__ import annotations

import os
from typing import AsyncIterator, Optional

import structlog

from app.core.config import settings

try:
    import aioboto3
    from botocore.config import Config
except ImportError:  # pragma: no cover - object-store path disabled without the dep
    aioboto3 = None
    Config = None

logger = structlog.get_logger()

_CHUNK = 1 << 20  # 1 MiB streaming chunks


def export_object_key(job_id: str, extension: str) -> str:
    ext = extension.lstrip(".")
    return f"exports/{job_id}.{ext}"


class ExportStore:
    def __init__(self, session=None):
        self._session = session or (aioboto3.Session() if aioboto3 is not None else None)
        self.bucket = settings.S3_EXPORT_BUCKET

    @property
    def enabled(self) -> bool:
        """True only when S3 storage is turned on AND the client is available."""
        return bool(settings.EXPORT_USE_S3) and self._session is not None

    def _client(self):
        cfg = Config(
            s3={"addressing_style": "path"},  # required for SeaweedFS/MinIO
            signature_version="s3v4",
            retries={"max_attempts": 3, "mode": "standard"},
        )
        return self._session.client(
            "s3",
            endpoint_url=settings.S3_ENDPOINT_URL,
            aws_access_key_id=settings.S3_ACCESS_KEY,
            aws_secret_access_key=settings.S3_SECRET_KEY,
            region_name=settings.S3_REGION,
            config=cfg,
        )

    async def ensure_bucket(self) -> None:
        async with self._client() as s3:
            try:
                await s3.head_bucket(Bucket=self.bucket)
            except Exception:  # noqa: BLE001 - head fails when absent; create it
                try:
                    await s3.create_bucket(Bucket=self.bucket)
                except Exception as exc:  # noqa: BLE001 - tolerate a concurrent create
                    logger.warning("export_store_bucket_create_failed", error=str(exc))

    async def upload_file(self, key: str, local_path: str) -> None:
        """Upload a local file to the export bucket (multipart via upload_file)."""
        async with self._client() as s3:
            await s3.upload_file(local_path, self.bucket, key)

    async def download_stream(self, key: str) -> AsyncIterator[bytes]:
        """Yield the object's bytes in chunks (for a StreamingResponse).

        The client stays open for the life of the generator, so the caller must
        consume it promptly — which StreamingResponse does.
        """
        async with self._client() as s3:
            resp = await s3.get_object(Bucket=self.bucket, Key=key)
            async with resp["Body"] as body:
                while True:
                    chunk = await body.read(_CHUNK)
                    if not chunk:
                        break
                    yield chunk

    async def exists(self, key: str) -> bool:
        try:
            async with self._client() as s3:
                await s3.head_object(Bucket=self.bucket, Key=key)
            return True
        except Exception:  # noqa: BLE001 - any error (incl. 404) means "not present"
            return False

    async def delete(self, key: str) -> None:
        try:
            async with self._client() as s3:
                await s3.delete_object(Bucket=self.bucket, Key=key)
        except Exception as exc:  # noqa: BLE001 - best-effort cleanup
            logger.warning("export_store_delete_failed", key=key, error=str(exc))


_export_store: Optional[ExportStore] = None


def get_export_store() -> ExportStore:
    global _export_store
    if _export_store is None:
        _export_store = ExportStore()
    return _export_store
