-- 033_rls_backfill.sql (FS-56)
-- GENERATED by backend/scripts/gen_033.py from 011/020/021 — do not edit by
-- hand; edit the source migration and re-run the generator.
--
-- Why: 011/020/021 run before 030 creates (and 032 type-converts) the yard/
-- transport/geotab/session/erp tables, so their guards skip those tables on a
-- fresh or legacy build. This file re-runs the exact same guarded, idempotent
-- blocks at the end of the chain when every table exists with final types.

-- from 011_tenant_isolation_rls.sql
-- assets: guarded — created later in the chain (030) on fresh builds;
-- 033_rls_backfill re-applies for tables this skips.
DO $$
BEGIN
  IF to_regclass('public.assets') IS NOT NULL AND NOT EXISTS (
    -- legacy varchar org column: the ::uuid policy qual would fail at
    -- CREATE POLICY; 032 converts the type, 033 re-applies this policy
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='assets'
      AND column_name='organization_id' AND data_type='character varying'
  ) THEN
    -- ---- Core manufacturing ----
    ALTER TABLE assets ENABLE ROW LEVEL SECURITY;
    ALTER TABLE assets FORCE  ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON assets;
    CREATE POLICY tenant_isolation ON assets
      FOR ALL
      USING      (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
      WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
  END IF;
END $$;

-- from 011_tenant_isolation_rls.sql
-- workcells: guarded — created later in the chain (030) on fresh builds;
-- 033_rls_backfill re-applies for tables this skips.
DO $$
BEGIN
  IF to_regclass('public.workcells') IS NOT NULL AND NOT EXISTS (
    -- legacy varchar org column: the ::uuid policy qual would fail at
    -- CREATE POLICY; 032 converts the type, 033 re-applies this policy
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='workcells'
      AND column_name='organization_id' AND data_type='character varying'
  ) THEN
    ALTER TABLE workcells ENABLE ROW LEVEL SECURITY;
    ALTER TABLE workcells FORCE  ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON workcells;
    CREATE POLICY tenant_isolation ON workcells
      FOR ALL
      USING      (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
      WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
  END IF;
END $$;

-- from 011_tenant_isolation_rls.sql
-- commands: guarded — created later in the chain (030) on fresh builds;
-- 033_rls_backfill re-applies for tables this skips.
DO $$
BEGIN
  IF to_regclass('public.commands') IS NOT NULL AND NOT EXISTS (
    -- legacy varchar org column: the ::uuid policy qual would fail at
    -- CREATE POLICY; 032 converts the type, 033 re-applies this policy
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='commands'
      AND column_name='organization_id' AND data_type='character varying'
  ) THEN
    ALTER TABLE commands ENABLE ROW LEVEL SECURITY;
    ALTER TABLE commands FORCE  ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON commands;
    CREATE POLICY tenant_isolation ON commands
      FOR ALL
      USING      (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
      WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
  END IF;
END $$;

-- from 011_tenant_isolation_rls.sql
-- yard_trailers: guarded — created later in the chain (030) on fresh builds;
-- 033_rls_backfill re-applies for tables this skips.
DO $$
BEGIN
  IF to_regclass('public.yard_trailers') IS NOT NULL AND NOT EXISTS (
    -- legacy varchar org column: the ::uuid policy qual would fail at
    -- CREATE POLICY; 032 converts the type, 033 re-applies this policy
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='yard_trailers'
      AND column_name='organization_id' AND data_type='character varying'
  ) THEN
    -- ---- Yard management ----
    ALTER TABLE yard_trailers ENABLE ROW LEVEL SECURITY;
    ALTER TABLE yard_trailers FORCE  ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON yard_trailers;
    CREATE POLICY tenant_isolation ON yard_trailers
      FOR ALL
      USING      (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
      WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
  END IF;
END $$;

-- from 011_tenant_isolation_rls.sql
-- dock_doors: guarded — created later in the chain (030) on fresh builds;
-- 033_rls_backfill re-applies for tables this skips.
DO $$
BEGIN
  IF to_regclass('public.dock_doors') IS NOT NULL AND NOT EXISTS (
    -- legacy varchar org column: the ::uuid policy qual would fail at
    -- CREATE POLICY; 032 converts the type, 033 re-applies this policy
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='dock_doors'
      AND column_name='organization_id' AND data_type='character varying'
  ) THEN
    ALTER TABLE dock_doors ENABLE ROW LEVEL SECURITY;
    ALTER TABLE dock_doors FORCE  ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON dock_doors;
    CREATE POLICY tenant_isolation ON dock_doors
      FOR ALL
      USING      (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
      WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
  END IF;
END $$;

-- from 011_tenant_isolation_rls.sql
-- yard_moves: guarded — created later in the chain (030) on fresh builds;
-- 033_rls_backfill re-applies for tables this skips.
DO $$
BEGIN
  IF to_regclass('public.yard_moves') IS NOT NULL AND NOT EXISTS (
    -- legacy varchar org column: the ::uuid policy qual would fail at
    -- CREATE POLICY; 032 converts the type, 033 re-applies this policy
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='yard_moves'
      AND column_name='organization_id' AND data_type='character varying'
  ) THEN
    ALTER TABLE yard_moves ENABLE ROW LEVEL SECURITY;
    ALTER TABLE yard_moves FORCE  ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON yard_moves;
    CREATE POLICY tenant_isolation ON yard_moves
      FOR ALL
      USING      (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
      WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
  END IF;
END $$;

-- from 011_tenant_isolation_rls.sql
-- driver_wait_times: guarded — created later in the chain (030) on fresh builds;
-- 033_rls_backfill re-applies for tables this skips.
DO $$
BEGIN
  IF to_regclass('public.driver_wait_times') IS NOT NULL AND NOT EXISTS (
    -- legacy varchar org column: the ::uuid policy qual would fail at
    -- CREATE POLICY; 032 converts the type, 033 re-applies this policy
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='driver_wait_times'
      AND column_name='organization_id' AND data_type='character varying'
  ) THEN
    ALTER TABLE driver_wait_times ENABLE ROW LEVEL SECURITY;
    ALTER TABLE driver_wait_times FORCE  ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON driver_wait_times;
    CREATE POLICY tenant_isolation ON driver_wait_times
      FOR ALL
      USING      (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
      WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
  END IF;
END $$;

-- from 011_tenant_isolation_rls.sql
-- yard_checkpoints: guarded — created later in the chain (030) on fresh builds;
-- 033_rls_backfill re-applies for tables this skips.
DO $$
BEGIN
  IF to_regclass('public.yard_checkpoints') IS NOT NULL AND NOT EXISTS (
    -- legacy varchar org column: the ::uuid policy qual would fail at
    -- CREATE POLICY; 032 converts the type, 033 re-applies this policy
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='yard_checkpoints'
      AND column_name='organization_id' AND data_type='character varying'
  ) THEN
    ALTER TABLE yard_checkpoints ENABLE ROW LEVEL SECURITY;
    ALTER TABLE yard_checkpoints FORCE  ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON yard_checkpoints;
    CREATE POLICY tenant_isolation ON yard_checkpoints
      FOR ALL
      USING      (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
      WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
  END IF;
END $$;

-- from 011_tenant_isolation_rls.sql
-- carriers: guarded — created later in the chain (030) on fresh builds;
-- 033_rls_backfill re-applies for tables this skips.
DO $$
BEGIN
  IF to_regclass('public.carriers') IS NOT NULL AND NOT EXISTS (
    -- legacy varchar org column: the ::uuid policy qual would fail at
    -- CREATE POLICY; 032 converts the type, 033 re-applies this policy
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='carriers'
      AND column_name='organization_id' AND data_type='character varying'
  ) THEN
    -- ---- Transportation / logistics ----
    ALTER TABLE carriers ENABLE ROW LEVEL SECURITY;
    ALTER TABLE carriers FORCE  ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON carriers;
    CREATE POLICY tenant_isolation ON carriers
      FOR ALL
      USING      (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
      WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
  END IF;
END $$;

-- from 011_tenant_isolation_rls.sql
-- drivers: guarded — created later in the chain (030) on fresh builds;
-- 033_rls_backfill re-applies for tables this skips.
DO $$
BEGIN
  IF to_regclass('public.drivers') IS NOT NULL AND NOT EXISTS (
    -- legacy varchar org column: the ::uuid policy qual would fail at
    -- CREATE POLICY; 032 converts the type, 033 re-applies this policy
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='drivers'
      AND column_name='organization_id' AND data_type='character varying'
  ) THEN
    ALTER TABLE drivers ENABLE ROW LEVEL SECURITY;
    ALTER TABLE drivers FORCE  ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON drivers;
    CREATE POLICY tenant_isolation ON drivers
      FOR ALL
      USING      (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
      WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
  END IF;
END $$;

-- from 011_tenant_isolation_rls.sql
-- shipments: guarded — created later in the chain (030) on fresh builds;
-- 033_rls_backfill re-applies for tables this skips.
DO $$
BEGIN
  IF to_regclass('public.shipments') IS NOT NULL AND NOT EXISTS (
    -- legacy varchar org column: the ::uuid policy qual would fail at
    -- CREATE POLICY; 032 converts the type, 033 re-applies this policy
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='shipments'
      AND column_name='organization_id' AND data_type='character varying'
  ) THEN
    ALTER TABLE shipments ENABLE ROW LEVEL SECURITY;
    ALTER TABLE shipments FORCE  ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON shipments;
    CREATE POLICY tenant_isolation ON shipments
      FOR ALL
      USING      (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
      WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
  END IF;
END $$;

-- from 011_tenant_isolation_rls.sql
-- routes: guarded — created later in the chain (030) on fresh builds;
-- 033_rls_backfill re-applies for tables this skips.
DO $$
BEGIN
  IF to_regclass('public.routes') IS NOT NULL AND NOT EXISTS (
    -- legacy varchar org column: the ::uuid policy qual would fail at
    -- CREATE POLICY; 032 converts the type, 033 re-applies this policy
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='routes'
      AND column_name='organization_id' AND data_type='character varying'
  ) THEN
    ALTER TABLE routes ENABLE ROW LEVEL SECURITY;
    ALTER TABLE routes FORCE  ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON routes;
    CREATE POLICY tenant_isolation ON routes
      FOR ALL
      USING      (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
      WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
  END IF;
END $$;

-- from 011_tenant_isolation_rls.sql
-- load_plans: guarded — created later in the chain (030) on fresh builds;
-- 033_rls_backfill re-applies for tables this skips.
DO $$
BEGIN
  IF to_regclass('public.load_plans') IS NOT NULL AND NOT EXISTS (
    -- legacy varchar org column: the ::uuid policy qual would fail at
    -- CREATE POLICY; 032 converts the type, 033 re-applies this policy
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='load_plans'
      AND column_name='organization_id' AND data_type='character varying'
  ) THEN
    ALTER TABLE load_plans ENABLE ROW LEVEL SECURITY;
    ALTER TABLE load_plans FORCE  ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON load_plans;
    CREATE POLICY tenant_isolation ON load_plans
      FOR ALL
      USING      (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
      WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
  END IF;
END $$;

-- from 011_tenant_isolation_rls.sql
-- freight_charges: guarded — created later in the chain (030) on fresh builds;
-- 033_rls_backfill re-applies for tables this skips.
DO $$
BEGIN
  IF to_regclass('public.freight_charges') IS NOT NULL AND NOT EXISTS (
    -- legacy varchar org column: the ::uuid policy qual would fail at
    -- CREATE POLICY; 032 converts the type, 033 re-applies this policy
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='freight_charges'
      AND column_name='organization_id' AND data_type='character varying'
  ) THEN
    ALTER TABLE freight_charges ENABLE ROW LEVEL SECURITY;
    ALTER TABLE freight_charges FORCE  ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON freight_charges;
    CREATE POLICY tenant_isolation ON freight_charges
      FOR ALL
      USING      (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
      WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
  END IF;
END $$;

-- from 011_tenant_isolation_rls.sql
-- dock_appointments: guarded — created later in the chain (030) on fresh builds;
-- 033_rls_backfill re-applies for tables this skips.
DO $$
BEGIN
  IF to_regclass('public.dock_appointments') IS NOT NULL AND NOT EXISTS (
    -- legacy varchar org column: the ::uuid policy qual would fail at
    -- CREATE POLICY; 032 converts the type, 033 re-applies this policy
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='dock_appointments'
      AND column_name='organization_id' AND data_type='character varying'
  ) THEN
    ALTER TABLE dock_appointments ENABLE ROW LEVEL SECURITY;
    ALTER TABLE dock_appointments FORCE  ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON dock_appointments;
    CREATE POLICY tenant_isolation ON dock_appointments
      FOR ALL
      USING      (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
      WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
  END IF;
END $$;

-- from 011_tenant_isolation_rls.sql
-- truck_asset_correlations: guarded — created later in the chain (030) on fresh builds;
-- 033_rls_backfill re-applies for tables this skips.
DO $$
BEGIN
  IF to_regclass('public.truck_asset_correlations') IS NOT NULL AND NOT EXISTS (
    -- legacy varchar org column: the ::uuid policy qual would fail at
    -- CREATE POLICY; 032 converts the type, 033 re-applies this policy
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='truck_asset_correlations'
      AND column_name='organization_id' AND data_type='character varying'
  ) THEN
    ALTER TABLE truck_asset_correlations ENABLE ROW LEVEL SECURITY;
    ALTER TABLE truck_asset_correlations FORCE  ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON truck_asset_correlations;
    CREATE POLICY tenant_isolation ON truck_asset_correlations
      FOR ALL
      USING      (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
      WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
  END IF;
END $$;

-- from 011_tenant_isolation_rls.sql
-- load_quality_logs: guarded — created later in the chain (030) on fresh builds;
-- 033_rls_backfill re-applies for tables this skips.
DO $$
BEGIN
  IF to_regclass('public.load_quality_logs') IS NOT NULL AND NOT EXISTS (
    -- legacy varchar org column: the ::uuid policy qual would fail at
    -- CREATE POLICY; 032 converts the type, 033 re-applies this policy
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='load_quality_logs'
      AND column_name='organization_id' AND data_type='character varying'
  ) THEN
    ALTER TABLE load_quality_logs ENABLE ROW LEVEL SECURITY;
    ALTER TABLE load_quality_logs FORCE  ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON load_quality_logs;
    CREATE POLICY tenant_isolation ON load_quality_logs
      FOR ALL
      USING      (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
      WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
  END IF;
END $$;

-- from 011_tenant_isolation_rls.sql
-- task_boards: guarded — created later in the chain (030) on fresh builds;
-- 033_rls_backfill re-applies for tables this skips.
DO $$
BEGIN
  IF to_regclass('public.task_boards') IS NOT NULL AND NOT EXISTS (
    -- legacy varchar org column: the ::uuid policy qual would fail at
    -- CREATE POLICY; 032 converts the type, 033 re-applies this policy
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='task_boards'
      AND column_name='organization_id' AND data_type='character varying'
  ) THEN
    -- ---- Kanban / task management ----
    ALTER TABLE task_boards ENABLE ROW LEVEL SECURITY;
    ALTER TABLE task_boards FORCE  ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON task_boards;
    CREATE POLICY tenant_isolation ON task_boards
      FOR ALL
      USING      (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
      WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
  END IF;
END $$;

-- from 011_tenant_isolation_rls.sql
-- task_rules: guarded — created later in the chain (030) on fresh builds;
-- 033_rls_backfill re-applies for tables this skips.
DO $$
BEGIN
  IF to_regclass('public.task_rules') IS NOT NULL AND NOT EXISTS (
    -- legacy varchar org column: the ::uuid policy qual would fail at
    -- CREATE POLICY; 032 converts the type, 033 re-applies this policy
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='task_rules'
      AND column_name='organization_id' AND data_type='character varying'
  ) THEN
    ALTER TABLE task_rules ENABLE ROW LEVEL SECURITY;
    ALTER TABLE task_rules FORCE  ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON task_rules;
    CREATE POLICY tenant_isolation ON task_rules
      FOR ALL
      USING      (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
      WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
  END IF;
END $$;

-- from 011_tenant_isolation_rls.sql
-- actionable_registries: guarded — created later in the chain (030) on fresh builds;
-- 033_rls_backfill re-applies for tables this skips.
DO $$
BEGIN
  IF to_regclass('public.actionable_registries') IS NOT NULL AND NOT EXISTS (
    -- legacy varchar org column: the ::uuid policy qual would fail at
    -- CREATE POLICY; 032 converts the type, 033 re-applies this policy
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='actionable_registries'
      AND column_name='organization_id' AND data_type='character varying'
  ) THEN
    ALTER TABLE actionable_registries ENABLE ROW LEVEL SECURITY;
    ALTER TABLE actionable_registries FORCE  ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON actionable_registries;
    CREATE POLICY tenant_isolation ON actionable_registries
      FOR ALL
      USING      (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
      WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
  END IF;
END $$;

-- from 011_tenant_isolation_rls.sql
-- data_correlations: guarded — created later in the chain (030) on fresh builds;
-- 033_rls_backfill re-applies for tables this skips.
DO $$
BEGIN
  IF to_regclass('public.data_correlations') IS NOT NULL AND NOT EXISTS (
    -- legacy varchar org column: the ::uuid policy qual would fail at
    -- CREATE POLICY; 032 converts the type, 033 re-applies this policy
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='data_correlations'
      AND column_name='organization_id' AND data_type='character varying'
  ) THEN
    -- ---- Correlation / analysis ----
    ALTER TABLE data_correlations ENABLE ROW LEVEL SECURITY;
    ALTER TABLE data_correlations FORCE  ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON data_correlations;
    CREATE POLICY tenant_isolation ON data_correlations
      FOR ALL
      USING      (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
      WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
  END IF;
END $$;

-- from 011_tenant_isolation_rls.sql
-- analysis_sessions: guarded — created later in the chain (030) on fresh builds;
-- 033_rls_backfill re-applies for tables this skips.
DO $$
BEGIN
  IF to_regclass('public.analysis_sessions') IS NOT NULL AND NOT EXISTS (
    -- legacy varchar org column: the ::uuid policy qual would fail at
    -- CREATE POLICY; 032 converts the type, 033 re-applies this policy
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='analysis_sessions'
      AND column_name='organization_id' AND data_type='character varying'
  ) THEN
    ALTER TABLE analysis_sessions ENABLE ROW LEVEL SECURITY;
    ALTER TABLE analysis_sessions FORCE  ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON analysis_sessions;
    CREATE POLICY tenant_isolation ON analysis_sessions
      FOR ALL
      USING      (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
      WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
  END IF;
END $$;

-- from 011_tenant_isolation_rls.sql
-- intake_items: guarded — created later in the chain (030) on fresh builds;
-- 033_rls_backfill re-applies for tables this skips.
DO $$
BEGIN
  IF to_regclass('public.intake_items') IS NOT NULL AND NOT EXISTS (
    -- legacy varchar org column: the ::uuid policy qual would fail at
    -- CREATE POLICY; 032 converts the type, 033 re-applies this policy
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='intake_items'
      AND column_name='organization_id' AND data_type='character varying'
  ) THEN
    ALTER TABLE intake_items ENABLE ROW LEVEL SECURITY;
    ALTER TABLE intake_items FORCE  ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON intake_items;
    CREATE POLICY tenant_isolation ON intake_items
      FOR ALL
      USING      (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
      WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
  END IF;
END $$;

-- from 011_tenant_isolation_rls.sql
-- geotab_trips: guarded — created later in the chain (030) on fresh builds;
-- 033_rls_backfill re-applies for tables this skips.
DO $$
BEGIN
  IF to_regclass('public.geotab_trips') IS NOT NULL AND NOT EXISTS (
    -- legacy varchar org column: the ::uuid policy qual would fail at
    -- CREATE POLICY; 032 converts the type, 033 re-applies this policy
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='geotab_trips'
      AND column_name='organization_id' AND data_type='character varying'
  ) THEN
    ALTER TABLE geotab_trips ENABLE ROW LEVEL SECURITY;
    ALTER TABLE geotab_trips FORCE  ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON geotab_trips;
    CREATE POLICY tenant_isolation ON geotab_trips
      FOR ALL
      USING      (organization_id IS NULL
                  OR organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
      WITH CHECK (organization_id IS NULL
                  OR organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
  END IF;
END $$;

-- from 011_tenant_isolation_rls.sql
-- geotab_diagnostics: guarded — created later in the chain (030) on fresh builds;
-- 033_rls_backfill re-applies for tables this skips.
DO $$
BEGIN
  IF to_regclass('public.geotab_diagnostics') IS NOT NULL AND NOT EXISTS (
    -- legacy varchar org column: the ::uuid policy qual would fail at
    -- CREATE POLICY; 032 converts the type, 033 re-applies this policy
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='geotab_diagnostics'
      AND column_name='organization_id' AND data_type='character varying'
  ) THEN
    ALTER TABLE geotab_diagnostics ENABLE ROW LEVEL SECURITY;
    ALTER TABLE geotab_diagnostics FORCE  ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON geotab_diagnostics;
    CREATE POLICY tenant_isolation ON geotab_diagnostics
      FOR ALL
      USING      (organization_id IS NULL
                  OR organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
      WITH CHECK (organization_id IS NULL
                  OR organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
  END IF;
END $$;

-- from 011_tenant_isolation_rls.sql
-- geotab_exceptions: guarded — created later in the chain (030) on fresh builds;
-- 033_rls_backfill re-applies for tables this skips.
DO $$
BEGIN
  IF to_regclass('public.geotab_exceptions') IS NOT NULL AND NOT EXISTS (
    -- legacy varchar org column: the ::uuid policy qual would fail at
    -- CREATE POLICY; 032 converts the type, 033 re-applies this policy
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='geotab_exceptions'
      AND column_name='organization_id' AND data_type='character varying'
  ) THEN
    ALTER TABLE geotab_exceptions ENABLE ROW LEVEL SECURITY;
    ALTER TABLE geotab_exceptions FORCE  ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON geotab_exceptions;
    CREATE POLICY tenant_isolation ON geotab_exceptions
      FOR ALL
      USING      (organization_id IS NULL
                  OR organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
      WITH CHECK (organization_id IS NULL
                  OR organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
  END IF;
END $$;

-- from 011_tenant_isolation_rls.sql
-- audit_logs: guarded — created later in the chain (030) on fresh builds;
-- 033_rls_backfill re-applies for tables this skips.
DO $$
BEGIN
  IF to_regclass('public.audit_logs') IS NOT NULL AND NOT EXISTS (
    -- legacy varchar org column: the ::uuid policy qual would fail at
    -- CREATE POLICY; 032 converts the type, 033 re-applies this policy
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='audit_logs'
      AND column_name='organization_id' AND data_type='character varying'
  ) THEN
    ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
    ALTER TABLE audit_logs FORCE  ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON audit_logs;
    CREATE POLICY tenant_isolation ON audit_logs
      FOR ALL
      USING      (organization_id IS NULL
                  OR organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
      WITH CHECK (organization_id IS NULL
                  OR organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
  END IF;
END $$;

-- from 011_tenant_isolation_rls.sql
-- data_processing_records: guarded — created later in the chain (030) on fresh builds;
-- 033_rls_backfill re-applies for tables this skips.
DO $$
BEGIN
  IF to_regclass('public.data_processing_records') IS NOT NULL AND NOT EXISTS (
    -- legacy varchar org column: the ::uuid policy qual would fail at
    -- CREATE POLICY; 032 converts the type, 033 re-applies this policy
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='data_processing_records'
      AND column_name='organization_id' AND data_type='character varying'
  ) THEN
    ALTER TABLE data_processing_records ENABLE ROW LEVEL SECURITY;
    ALTER TABLE data_processing_records FORCE  ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON data_processing_records;
    CREATE POLICY tenant_isolation ON data_processing_records
      FOR ALL
      USING      (organization_id IS NULL
                  OR organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
      WITH CHECK (organization_id IS NULL
                  OR organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
  END IF;
END $$;

-- from 011_tenant_isolation_rls.sql
-- integration_configurations: guarded — created later in the chain (030) on fresh builds;
-- 033_rls_backfill re-applies for tables this skips.
DO $$
BEGIN
  IF to_regclass('public.integration_configurations') IS NOT NULL AND NOT EXISTS (
    -- legacy varchar org column: the ::uuid policy qual would fail at
    -- CREATE POLICY; 032 converts the type, 033 re-applies this policy
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='integration_configurations'
      AND column_name='organization_id' AND data_type='character varying'
  ) THEN
    ALTER TABLE integration_configurations ENABLE ROW LEVEL SECURITY;
    ALTER TABLE integration_configurations FORCE  ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS tenant_isolation ON integration_configurations;
    CREATE POLICY tenant_isolation ON integration_configurations
      FOR ALL
      USING      (organization_id IS NULL
                  OR organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
      WITH CHECK (organization_id IS NULL
                  OR organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
  END IF;
END $$;

-- from 020_erp_integration_tables.sql
-- Row-level security policies for multi-tenant isolation
-- FS-56: these policies originally said TO authenticated_users (a role that
-- never existed anywhere — the file could not apply) and keyed on the
-- app.current_organization_id GUC (which nothing sets; the canonical GUC is
-- app.current_org_id, see 011). Rewritten to the codebase convention so ERP
-- tenant isolation actually enforces.
DO $$
BEGIN
  IF to_regclass('public.erp_integration_events') IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='erp_integration_events'
      AND column_name='organization_id' AND data_type='character varying'
  ) THEN
    ALTER TABLE erp_integration_events ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS erp_events_org_isolation ON erp_integration_events;
    CREATE POLICY erp_events_org_isolation ON erp_integration_events
        FOR ALL
        USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
  END IF;
END $$;

-- from 020_erp_integration_tables.sql
DO $$
BEGIN
  IF to_regclass('public.erp_data_mappings') IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='erp_data_mappings'
      AND column_name='organization_id' AND data_type='character varying'
  ) THEN
    ALTER TABLE erp_data_mappings ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS erp_mappings_org_isolation ON erp_data_mappings;
    CREATE POLICY erp_mappings_org_isolation ON erp_data_mappings
        FOR ALL
        USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
  END IF;
END $$;

-- from 020_erp_integration_tables.sql
DO $$
BEGIN
  IF to_regclass('public.erp_sync_status') IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='erp_sync_status'
      AND column_name='organization_id' AND data_type='character varying'
  ) THEN
    ALTER TABLE erp_sync_status ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS erp_sync_org_isolation ON erp_sync_status;
    CREATE POLICY erp_sync_org_isolation ON erp_sync_status
        FOR ALL
        USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
  END IF;
END $$;

-- from 020_erp_integration_tables.sql
DO $$
BEGIN
  IF to_regclass('public.erp_entities') IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='erp_entities'
      AND column_name='organization_id' AND data_type='character varying'
  ) THEN
    ALTER TABLE erp_entities ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS erp_entities_org_isolation ON erp_entities;
    CREATE POLICY erp_entities_org_isolation ON erp_entities
        FOR ALL
        USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
  END IF;
END $$;

-- from 020_erp_integration_tables.sql
DO $$
BEGIN
  IF to_regclass('public.erp_correlations') IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='erp_correlations'
      AND column_name='organization_id' AND data_type='character varying'
  ) THEN
    ALTER TABLE erp_correlations ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS erp_correlations_org_isolation ON erp_correlations;
    CREATE POLICY erp_correlations_org_isolation ON erp_correlations
        FOR ALL
        USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
  END IF;
END $$;

-- from 021_intake_cross_correlation.sql
DO $$
BEGIN
  IF to_regclass('public.intake_items') IS NOT NULL THEN
    ALTER TABLE intake_items
    ADD COLUMN IF NOT EXISTS shared_keys JSON DEFAULT '[]',
    ADD COLUMN IF NOT EXISTS structure_metadata JSON DEFAULT '{}',
    ADD COLUMN IF NOT EXISTS processing_time_seconds INTEGER;

    CREATE INDEX IF NOT EXISTS idx_intake_items_shared_keys
        ON intake_items USING GIN ((shared_keys::jsonb));

    COMMENT ON COLUMN intake_items.shared_keys IS 'Normalized shared keys (asset_id, date, order_number, etc.) extracted from filename, metadata, and content for cross-file correlation';
    COMMENT ON COLUMN intake_items.structure_metadata IS 'Document structure info (page_count, section_count, tables, headers) for PDF/DOCX/image parsing';
    COMMENT ON COLUMN intake_items.processing_time_seconds IS 'Actual time in seconds taken to parse and process the file (for estimation calibration)';
  END IF;

  IF to_regclass('public.session_data_sources') IS NOT NULL THEN
    ALTER TABLE session_data_sources
    ADD COLUMN IF NOT EXISTS shared_keys JSON DEFAULT '[]',
    ADD COLUMN IF NOT EXISTS structure_metadata JSON DEFAULT '{}';

    CREATE INDEX IF NOT EXISTS idx_session_data_sources_shared_keys
        ON session_data_sources USING GIN ((shared_keys::jsonb));

    COMMENT ON COLUMN session_data_sources.shared_keys IS 'Normalized shared keys for cross-file correlation within analysis sessions';
    COMMENT ON COLUMN session_data_sources.structure_metadata IS 'Document structure info for session data sources';
  END IF;
END $$;
